### ISSUE TITLE
port definition in parameter -bindaddr not working

### ISSUE THREAD

**Issue by henrythasler** [OperatorFoundation/shapeshifter-dispatcher#3]
Action: 
`bin/shapeshifter-dispatcher -client -transparent -ptversion 2 -transports obfs2 -state state -target 192.168.178.46:2222 -bindaddr obfs2-127.0.0.1:56789 -logLevel DEBUG -enableLogging &`

Expected result:
shapeshifter listens on port 56789

Observed behavior: listener port 1234 is always used, no matter what is given with -bindaddr <PROTO>-<IP>:<PORT>
`$ netstat -tlnp`
`(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN      -                   
`

**Comment by divinebird** [comment]
You may use such arguments I think after new update
-proxylistenaddr 127.0.0.1:56789

**Comment by blanu** [comment]
This should be resolved now.

Here is an example command line that has been tested and works:

bin/shapeshifter-dispatcher -transparent -server -state state -orport 127.0.0.1:3333 -transports obfs4 -bindaddr obfs4-127.0.0.1:2222 -logLevel DEBUG -enableLogging -extorport 127.0.0.1:3334 -options '{"obfs4": {"cert": "gahG4eoXDiLwtQ/JLRLAf6icw3fBoq4s66oVhAIdVrzoMtSdXDh2EW+n7r3oXoEGJGULPQ", "iatMode": "0"}}'

I have confirmed that in this example the server listens on port 2222.

**Comment by blanu** [comment]
There is no way official way to specify a binding address or port for a client. This is an issue inherited from the PT 1.0 specification, in which the client always picks a port and then informs the host application which port it has chosen. The -bindaddr flag is only for specifying the port when running in -server mode.

As mentioned in the comment above, the -proxylistenaddr flag has been added as an experimental extension to specify the binding address and port for -client mode as this is a commonly requested and useful feature. However, it is not officially supported as it is not part of the specification. Should we instead allow the -bindaddr flag be used in both -client and -server modes? Well it seems intuitive. However, shapeshifter-dispatcher is a reference implementation of the PT 2.1 draft 1 specification. So in order to provide this behavior, it would added as a proposal and then accepted into the specification. Please feel free to create a proposal here: https://github.com/Pluggable-Transports/Pluggable-Transports-spec
