### ISSUE TITLE
Client listening port can not be modified

### ISSUE THREAD

**Issue by lizhengyong69** [OperatorFoundation/shapeshifter-dispatcher#5]
How to specify the client listening port, the client listening port can not be modified, always 1234.

**Comment by lizhengyong69** [comment]
IP can not bind the public network address，always 127.0.0.1:1234.

**Comment by blanu** [comment]
This issue should have been resolved in release 2.0.1: https://github.com/OperatorFoundation/shapeshifter-dispatcher/releases/tag/2.0.1

Please note that historically, there has not been a way to specify the client listening port. In the past, the SOCKS address was hardcoded to 127.0.0.1:0, which only allows binding to localhost and a random port.

Adding the new -proxylistenaddr command line flag allows for specifying both the IP and port to bind to for accepting client proxy requests, and has been added to PT2/SOCKS mode, transparent TCP mode, and both UDP modes.

This is currently an experimental extension not covered in the PT 2.0 specification and will be considered for inclusion in the PT 2.1 specification. If you have any feedback on how this feature should work, please discuss so that we can add the best possible version of this feature to the specification.
