### ISSUE TITLE
does DEBUG logging work for anyone?

### ISSUE THREAD

**Issue by MarpleA** [OperatorFoundation/shapeshifter-dispatcher#8]
Hi,

I set up the shapeshifter-dispatcher with obfs4 which causes me a lot of headaches, since the order of arguments is extremely important and needs to be completely different then in the example given. 
However, after having it up and running with the -enableLogging and -logLevel DEBUG, the only log I get is located in the file dispatcher.log. But with very limited information. e.g. the only info I get, is that the proxy is listening and in case there is a connection, it says "new connection".
Is there any chance to get a more detailed debug-like output from shapeshifter?

Best

**Comment by blanu** [comment]
The log file is the one you found in dispatcher.log. I think what you are experiencing is that there is a lack of logging in the actual transports itself (obfs4). We did not write obfs4, it's a fork of the code from obfs4proxy. obfs4 generally does not provide any useful logging information and so is hard to debug. The logging information you are seeing is probably from the general dispatcher code, which would therefore include anything specific about obfs4 internals.

I think that what would help you is to add additional DEBUG level logging lines to the obfs4 codebase. However, in order to know what logging lines would be useful, we would need to know more about what problems you are having so that we can provide logging lines that would be helpful to you in debugging your problem. Of course you can feel free to create a patch in which you add additional logging to obfs4 yourself, in which case we would be happy to accept it.

As this does not seem to be an issue with DEBUG logging not working, but rather with there be a lacking of using logging in obfs4, I will close this issue as this is an issue which should be filed on shapeshifter-transports and not shapeshifter-dispatcher.
